apiVersion: v1
kind: Secret
metadata:
  name: postgres-test-secret
type: Opaque
stringData:
  config-test.yaml: |
    auth:
      jwt_secret: "superdupersecret"
    database:
      host: "yagsy-postgres"
      port: 5432
      name: "yagsydb"
      driver: "postgres"
      user: "yagsy"
      password: "yagsy"